version: "3"
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./sonardata/sonarqube_data:/opt/sonarqube/data
      - ./sonardata/sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonardata/sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  db:
    container_name: sonarqube-db
    image: postgres
    hostname: db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - ./sonardata/postgresql:/var/lib/postgresql
      - ./sonardata/postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

